server:
  port: 8080

spring:
    datasource:
        name: twinkle
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.cj.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/twinkle?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
          username: root
          password: 123456
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    redis:
      #数据库索引
#      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      #连接超时时间
      timeout: 2000
      pool:
        #最大连接数
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 10
        #最小空闲
        min-idle: 0
        test-on-borrow: false
    deools:
        restart:
            #热部署生效
          enabled: true
#   devtools:
#        restart:
#          enabled: false  #设置开启热部署
app:
    signture:
        verification:
            enable: false               #接口签名校验开关
            token: twinkle_debug        #接口签名关闭时，放行标识,用于调试